version: '3.1'

services:
  mongo:
    image: mongo:4.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cr-db
    volumes:
      - /mongo/db_data:/data/db
      - /mongo/init:/docker-entrypoint-initdb.d